### ISSUE TITLE
Missing AP_VS_HOLD input

### ISSUE THREAD

**Issue by EpicDenmos** [Seahawk240/Microsoft-FS2020-To-Arduino#13]
The simconnect input **AP_VS_HOLD** allowing to set the autopilot in VS mode is missing from the application.

Seems to be undocumented but working.
See : https://forums.flightsimulator.com/t/vertical-speed-event-command-in-simconnect/278490

Should be added (or have a way to add it ourselve from the app)

**Comment by Seahawk240** [comment]
Thank You! Much appreciated. I will add it in. Later on I will include a function where you can add your own inputs/exports.

**Comment by Seahawk240** [comment]
After looking into it, i saw that you can actually set/send a custom value for every Output Value, changing the value in the Sim on the fly. I could include this functionality into my program but I'm not sure yet. What do you think?

**Comment by Seahawk240** [comment]
###Issue Closed for now###
