### ISSUE TITLE
Quality of Life -> Add your own Imports/Exports

### ISSUE THREAD

**Issue by Seahawk240** [Seahawk240/Microsoft-FS2020-To-Arduino#15]
Functionality to add Variables which aren't in the Export/Import list, which are needed for mods or are included in the game but not in the docu of the Sim.

**Comment by ollivier44** [comment]
Hello !
is it possible to import all of the vibrations of the plane (wheels, engine...) ?

**Comment by Seahawk240** [comment]
> 
> 
> Hello !
> is it possible to import all of the vibrations of the plane (wheels, engine...) ?

Hey Ollivier,
that's a good question. I did not find any info on variables import or export which mention vibrations except one. The one I found was about the engine vibrations. Do you've got any info about where I can find them? If there are some I'm sure we can get them in the program.

Greetings Matthias

**Comment by ollivier44** [comment]
I saw the engine vibrations but the value remains at zero. I'll look information on other data.
Thanks a lot !
Have a nice day ;)
Ollivier.
