### ISSUE TITLE
Variables from FS 2020

### ISSUE THREAD

**Issue by ollivier44** [Seahawk240/Microsoft-FS2020-To-Arduino#16]
Hello,
I test your program : it looks very good !
I want to recover some variables from FS2020.
What is the syntax to recover the COM ACTIVE FREQUENCY for example (ID 145, index 1) ?
Thanks
Ollivier.

**Comment by Seahawk240** [comment]
Hey Ollivier,

I'm so sorry that I'm so late with replying to you! I work on the first video about the program for the last weeks and had to work a lot besides that and I just forget to at this page. 

Now to your problem:
I don't really understand what do you mean by recover, could you explain that to me a little bit more?

Stay healthy and have a good week!
Greetings Matthias

**Comment by ollivier44** [comment]
Hello Matthias,
Thanks for you answer ! 
I found the answer to my first question but I noticed something :
I have to connect you EXE to my Arduino first, before connecting to FS2020, otherwise it doesn't work. Could you confirm that ?
You can see here a screen shot : https://www.infobat3d-data.com/?dl=b9f58fcf4368e31c52c92a1bef858ae8
Stay healthy too ;)
Regards, Ollivier

**Comment by Seahawk240** [comment]
> 
> 
> Hello Matthias,
> Thanks for you answer !
> I found the answer to my first question but I noticed something :
> I have to connect you EXE to my Arduino first, before connecting to FS2020, otherwise it doesn't work. Could you confirm that ?
> You can see here a screen shot : https://www.infobat3d-data.com/?dl=b9f58fcf4368e31c52c92a1bef858ae8
> Stay healthy too ;)
> Regards, Ollivier

Hey Ollivier,

I've looked into that problem and can confirm that it happens to me too. I think it's a problem on the Arduino side of things and espacially with my way of handling the data from the serial connection. I gonna add it to the list of issues and try to fix it in the next few days. 
But thanks very much for making me aware of this problem, I really apreciate it!

Greetings Matthias

**Comment by Seahawk240** [comment]
###Issue Closed for now###
