### ISSUE TITLE
Serial wont work if connecting to FS2020 first and Arduino afterwards.

### ISSUE THREAD

**Issue by Seahawk240** [Seahawk240/Microsoft-FS2020-To-Arduino#17]
As mentioned by @ollivier44 in his issue (see comment below) there is a problem which leads to the serial data transfer not working, if the Serial connection has not been connected before connecting to the Flight Sim. Hope to fix it soon.

Once again Thanks to Ollivier for bringing it to my attention!
Greetings Matthias

Hello Matthias,
Thanks for you answer ! 
I found the answer to my first question but I noticed something :
I have to connect you EXE to my Arduino first, before connecting to FS2020, otherwise it doesn't work. Could you confirm that ?
You can see here a screen shot : https://www.infobat3d-data.com/?dl=b9f58fcf4368e31c52c92a1bef858ae8
Stay healthy too ;)
Regards, Ollivier

_Originally posted by @ollivier44 in https://github.com/Seahawk240/Microsoft-FS2020-To-Arduino/issues/16#issuecomment-770690590_

**Comment by ollivier44** [comment]
Hi,
thank you for your answer ! 
Ollivier.

**Comment by Seahawk240** [comment]
Okay found the cause and a solution to this problem. 

CAUSE:
The Arduino defaulty restarts/reset the moment a serial connection via USB (UART) is established. Because the Arduino basically does a reset and the program bombards it with serial Data right in the middle of it, our little Arduinos get a bit confused, at least that's what I think. 

SOLUTION:
I inserted a little 1 Second Delay in the program, so that the Serial Connection can be established correctly. 

ANYWAY:

That should fix the problem. If not let me know.
Thanks again to @ollivier44
Greetings Matthias

**Comment by ollivier44** [comment]
Hello Matthias,
Thanks a lot, iI will try it !
Have a nice day ;)

**Comment by Seahawk240** [comment]
> Hello Matthias,
> Thanks a lot, iI will try it !
> Have a nice day ;)

My pleasure, just keep in mind the new version isn't online yet, because there is one issue missing. I want to upload it within the next 2 days.

Greetings Matthias

**Comment by ollivier44** [comment]
ok, no problem !
