### ISSUE TITLE
Tweaks for COM-Port List

### ISSUE THREAD

**Issue by Seahawk240** [Seahawk240/Microsoft-FS2020-To-Arduino#19]
Following the idea of @Discman777 I gonna implement the following tweak to the Com Port List:

Quote:
2. When adding a Connection, can you default the COM port away from COM1?  As COM1 is the motherboard’s and is never the desired choice.  Perhaps defaulting to the second available COM?

_Originally posted by @Discman777 in https://github.com/Seahawk240/Microsoft-FS2020-To-Arduino/issues/5#issuecomment-768651661_

**Comment by Seahawk240** [comment]
Okay changed the defaults on that.

SOLUTION:
-When Adding a Connection:
1. If there is more than one COM-Port available take the second one
2. If only one is available choose the first COM-Port
3. If no COM-Port is available keep it blank (Not tested, don't know how; probably never happens so I don't mind for now)

-When Refreshing COM-Ports:
1. If the last selected is still available use this
2. If 1. Fails same behaviour as described above.

ANYWAY:
Thanks again to @Discman777 for the idea!

Greetings Matthias

**Comment by Discman777** [comment]
Tested Release 1.1.  COM port is now defaulting to second port.
Thanks for implementing this.
    Joe
