### ISSUE TITLE
Quality of Life -> "Send Data only when changed" - Functionality for Serial

### ISSUE THREAD

**Issue by Seahawk240** [Seahawk240/Microsoft-FS2020-To-Arduino#20]
Reintroduce of a "Send Data only when changed" like Functionality of an earlier version, for the serial Port Communication.
Thanks to @Discman777 for this idea!

3. I also wonder if it makes sense to filter the serial data packets coming out (i.e. from FS to Arduino)?  So that if the subsequent sample of the variable is unchanged, don’t output it to the serial port.  The trick is that it’s still necessary to output unchanged data packets at some less-frequent intervals; otherwise, static data may never be seen.  The PC has plenty of computing power to do the data testing and floating point rounding etc.  This could help out the weaker Arduino.

_Originally posted by @Discman777 in https://github.com/Seahawk240/Microsoft-FS2020-To-Arduino/issues/5#issuecomment-768651661_

**Comment by ollivier44** [comment]
I think it is a very good idea too.

**Comment by Discman777** [comment]
I’ve just submitted an alternative to this. :)

**Comment by Seahawk240** [comment]
CLOSED -> Discussion continued in: #37
