### ISSUE TITLE
[Feature Request]  Variable Filter

### ISSUE THREAD

**Issue by Discman777** [Seahawk240/Microsoft-FS2020-To-Arduino#27]
Since using your excellent software for the last two weeks, I’ve been able to access many operations and variables to and from the sim.  In the process searching though the hundreds of variable names, I thought of couple of GUI suggestions that might enhance the experience.

1. Add a filter for the “Exports” symbols dropdown list.  With it the list would show only those items matching the substring given. 

2. Over at the “Imports and Buttons” dialog, add a similar filter to pare down the list.

3. On the “Exports” side, you have the feature to show the running status of the variables.  Add the counterpart for the "Imports" dialog, by allowing the user to enter an ID# and a Value that will be sent to the sim with a click of a button.  This offers a quick and easy way to test out whether the selected candidate is right for the intended task.

Thanks, I’m looking forward to the continue enhancement of FS2020TA!

**Comment by Seahawk240** [comment]
Hey Joe,



> Since using your excellent software for the last two weeks, I’ve been able to access many operations and variables to and from the sim. In the process searching though the hundreds of variable names, I thought of couple of GUI suggestions that might enhance the experience.
>

I'm sorry for answering this late again but I like the Ideas!


=>To 1 and 2: this will take some time, espacially the substrings for the filter but I'll add it to the list

Original Comment:
> 1. Add a filter for the “Exports” symbols dropdown list.  With it the list would show only those items matching the substring given.
> 2. Over at the “Imports and Buttons” dialog, add a similar filter to pare down the list.


To 3.:  This is a very good idea too! Espacially once I implemented the option to add custom imports/exports. I probably gonna implement both along side.


> 3. On the “Exports” side, you have the feature to show the running status of the variables.  Add the counterpart for the "Imports" dialog, by allowing the user to enter an ID# and a Value that will be sent to the sim with a click of a button.  This offers a quick and easy way to test out whether the selected candidate is right for the intended task.


I'll add new issues for them soon and gonna think about a neat implemantation.
There are probably some more UI Changes coming up. All the new features make it nescassary. So there's hope that I will keep it all organized and easy to use :)

Greetings Matthias

**Comment by Seahawk240** [comment]
CLOSED -> continued in:

#38 
#39
