### ISSUE TITLE
What I'm up to -> Development 2nd March 2021

### ISSUE THREAD

**Issue by Seahawk240** [Seahawk240/Microsoft-FS2020-To-Arduino#31]
Hey there,

I succesfully finished my university exams for now. Although I've got some things to do this week (Starting my Bachelors Thesis and working) I hope to be able to continue development on the weekend. I'm not really sure how fast I will implement all the updates I've planned but I may work with subversions like before. For now I will change the deadline of the "Quality of Life Update" to March 17th, still hoping to bring You the update earlier. But we will see. Anyway thanks for your support, I wish you all a really good and healthy time!

Greetings Matthias

**Comment by ollivier44** [comment]
Well done for your exams !

**Comment by Seahawk240** [comment]
> 
> 
> Well done for your exams !

Thanks Man! :)
