### ISSUE TITLE
What I'm up to -> Development 22nd March 2021

### ISSUE THREAD

**Issue by Seahawk240** [Seahawk240/Microsoft-FS2020-To-Arduino#36]
Hello There...
It's been a while, I know. And my Deadlines did not work out the way i wanted them to either. Anyway... I'm nearly finished with the new Update, including:

- Auto-StartUp
- Custom Imports/Exports
- Save and Load Functionality for settings, connections and variables (including custom ones)
- A "Connect by Ident" Functionality which let's you Auto-Connect your devices by sending a commmand from the device to the program.
- An "Identify your Device" Functionality included in the Ident, which let's you send a specific device Name to the program. which is then being displayed.
- Correct Scaling and reformatting when changing the Window-Size
- Bugfixes
- Probably some new Bugs... But they will be fixed 😄 

Anyway I hope after all this time, there is still someone left to enjoy the new content.
In the next few weeks I will focus on implementing:

- A Serial Monitor
- Some Kind of Flow-Control for Serial-Data in the realm of Ideas presented by @Discman777 

The only things missing for the new Update are some new Help Pages and Testing. With that I think that's all for development,
For those who are interested what took me so long, here you go:

The last few weeks have been a bit turbulent to say the least. After my exams were finished I had to work most of my weeks. Besides that I helped my Brother with renovating his house, which he bought at the end of last year. 2 Weeks ago in the midst of all that, my Grand Mother died at a age of 85. I could not have wished for a better end for her and our family but it's a huge loss nethertheless. Her funeral and our final good bye was yesterday, gladly not too much affected by the ongoing Covid-Crisis. Afterwards I finally got the motivation and the capacity back to tackle the more intensive parts of this update. That went well and was a nice change. Anyway, I think these things were the main ones keeping me from adding value to this project. I hope everyone of you is doing well and is healthy.

Have good time
Matthias

**Comment by ollivier44** [comment]
Hello,
Is the new update avalable ?
Thanks,
Ollivier.

**Comment by ollivier44** [comment]
...and sorry for your grand Mother...

**Comment by Seahawk240** [comment]
Thanks and not yet. I want to upload it either tonight or tomorrow. Hope it will be up tonight.
It still needs some testing and some help pages.

**Comment by Seahawk240** [comment]
Okay the update went live yesterday. Took me longer because of some bugs I had to fix and all the new Help Pages, I'm sorry for that. But anyway I hope you all have fun with it!
For more look at Issue #41

**Comment by ollivier44** [comment]
Thanks a lot, I will try it the next week .
Fly safe ;)
Ollivier.
